package com.hbmpojos;

// Generated 15 Dec, 2015 1:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BusXdetails generated by hbm2java
 */
public class BusXdetails implements java.io.Serializable {

	private int serviceNo;
	private String name;
	private String type;
	private Date arrTime;
	private Date depTime;
	private String durationHrs;
	private Integer fare;
	private Integer avblSeats;

	public BusXdetails() {
	}

	public BusXdetails(int serviceNo) {
		this.serviceNo = serviceNo;
	}

	public BusXdetails(int serviceNo, String name, String type, Date arrTime,
			Date depTime, String durationHrs, Integer fare, Integer avblSeats) {
		this.serviceNo = serviceNo;
		this.name = name;
		this.type = type;
		this.arrTime = arrTime;
		this.depTime = depTime;
		this.durationHrs = durationHrs;
		this.fare = fare;
		this.avblSeats = avblSeats;
	}

	public int getServiceNo() {
		return this.serviceNo;
	}

	public void setServiceNo(int serviceNo) {
		this.serviceNo = serviceNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getArrTime() {
		return this.arrTime;
	}

	public void setArrTime(Date arrTime) {
		this.arrTime = arrTime;
	}

	public Date getDepTime() {
		return this.depTime;
	}

	public void setDepTime(Date depTime) {
		this.depTime = depTime;
	}

	public String getDurationHrs() {
		return this.durationHrs;
	}

	public void setDurationHrs(String durationHrs) {
		this.durationHrs = durationHrs;
	}

	public Integer getFare() {
		return this.fare;
	}

	public void setFare(Integer fare) {
		this.fare = fare;
	}

	public Integer getAvblSeats() {
		return this.avblSeats;
	}

	public void setAvblSeats(Integer avblSeats) {
		this.avblSeats = avblSeats;
	}

}
